apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DeploymentConstraint
metadata:
  name: deploymentconstraint
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "no-pods-namespace"